//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaFarmacia.Models.viewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_InvoiceDetail
    {
        public long Id { get; set; }
        public string InvoiceHeaderCode { get; set; }
        public string ProductCode { get; set; }
        public int Count { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Total { get; set; }
    
        public virtual T_InvoiceHeader T_InvoiceHeader { get; set; }
        public virtual T_Product T_Product { get; set; }
    }
}
