//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaFarmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncabezadoFactura()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public string CodigoFactura { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int IdentificacionCliente { get; set; }
        public int IdentificacionUsuario { get; set; }
        public int IdMetodoPago { get; set; }
        public decimal SubTotalFactura { get; set; }
        public decimal TotalFactura { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
