//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaFarmacia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LaFarmaciaDBEntities : DbContext
    {
        public LaFarmaciaDBEntities()
            : base("name=LaFarmaciaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Client> T_Client { get; set; }
        public virtual DbSet<T_InvoiceDetail> T_InvoiceDetail { get; set; }
        public virtual DbSet<T_InvoiceHeader> T_InvoiceHeader { get; set; }
        public virtual DbSet<T_MethodPay> T_MethodPay { get; set; }
        public virtual DbSet<T_Product> T_Product { get; set; }
        public virtual DbSet<T_ProductType> T_ProductType { get; set; }
        public virtual DbSet<T_Rol> T_Rol { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
    
        public virtual int SP_AddClient(string pName, string pEmail)
        {
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AddClient", pNameParameter, pEmailParameter);
        }
    
        public virtual ObjectResult<SP_CheckUser_Result> SP_CheckUser(string pEmail, string pPassword)
        {
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CheckUser_Result>("SP_CheckUser", pEmailParameter, pPasswordParameter);
        }
    
        public virtual int SP_UpdateUser(Nullable<int> pId, string pName, string pEmail, Nullable<int> pRolId, Nullable<bool> pState, string pPassword)
        {
            var pIdParameter = pId.HasValue ?
                new ObjectParameter("pId", pId) :
                new ObjectParameter("pId", typeof(int));
    
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            var pRolIdParameter = pRolId.HasValue ?
                new ObjectParameter("pRolId", pRolId) :
                new ObjectParameter("pRolId", typeof(int));
    
            var pStateParameter = pState.HasValue ?
                new ObjectParameter("pState", pState) :
                new ObjectParameter("pState", typeof(bool));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateUser", pIdParameter, pNameParameter, pEmailParameter, pRolIdParameter, pStateParameter, pPasswordParameter);
        }
    
        public virtual int SP_NewUser(string pName, string pEmail, Nullable<int> pRolId, Nullable<bool> pState, string pPassword)
        {
            var pNameParameter = pName != null ?
                new ObjectParameter("pName", pName) :
                new ObjectParameter("pName", typeof(string));
    
            var pEmailParameter = pEmail != null ?
                new ObjectParameter("pEmail", pEmail) :
                new ObjectParameter("pEmail", typeof(string));
    
            var pRolIdParameter = pRolId.HasValue ?
                new ObjectParameter("pRolId", pRolId) :
                new ObjectParameter("pRolId", typeof(int));
    
            var pStateParameter = pState.HasValue ?
                new ObjectParameter("pState", pState) :
                new ObjectParameter("pState", typeof(bool));
    
            var pPasswordParameter = pPassword != null ?
                new ObjectParameter("pPassword", pPassword) :
                new ObjectParameter("pPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NewUser", pNameParameter, pEmailParameter, pRolIdParameter, pStateParameter, pPasswordParameter);
        }
    }
}
