//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaFarmacia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.EncabezadoFactura = new HashSet<EncabezadoFactura>();
        }
    
        public int IdentificacionUsuario { get; set; }
        public string NombreCompletoUsuario { get; set; }
        public string CorreoElectronico { get; set; }
        public int IdTipoUsuario { get; set; }
        public int IdEstadoUsuario { get; set; }
        public string Contraseña { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncabezadoFactura> EncabezadoFactura { get; set; }
        public virtual EstadoUsuario EstadoUsuario { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
